# Generated by Django 4.2.12 on 2024-05-07 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_menuitem_nothing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='nothing',
        ),
    ]
